#!/usr/bin/env python3
"""Amalgamate the kernel headers into one Vulkan GLSL compute source.

Same job as amalgamate_cl.py, and the same rule: the text comes from the
headers every other backend compiles, so there is no second copy of the maths
to keep in step. The shim's CLAY_KERNEL_VULKAN branch does the dialect work
(tools/check_kernel_dialect.py compiles it on every push).

Two constructs cannot be macro'd away in the source, because the C-family
spelling is not expressible as a macro at all, so they are rewritten here:

  enum E { a = 0, b = 1 };   ->  const int a = 0; const int b = 1;
  typedef struct XT {...} X; ->  struct X {...};

Both are local, syntactic, and verified by the shader compile that follows:
if either transform mangles something, glslang rejects the result rather than
a wrong field reaching a device.
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
INCLUDE_RE = re.compile(r'^\s*#\s*include\s+"(clay/[^"]+)"\s*$')

# Storage the shim's CLAY_AT / CLAY_INSTR_* macros read through. Declared
# ahead of the headers because GLSL has no forward declarations for these.
PREAMBLE = """#version 460
// GENERATED by tools/amalgamate_glsl.py -- do not edit.
// Source of truth: include/clay/kernel/*.h, compiled with CLAY_KERNEL_VULKAN.
#define CLAY_KERNEL_VULKAN 1

layout(local_size_x = 64) in;

// The tape's instruction stream, as pairs of uints (op, param_offset). A
// struct-of-two-uints SSBO would need std430 padding rules to agree with the
// host's CTapeInstr; a flat uint array cannot disagree.
layout(set = 0, binding = 0) readonly buffer ClayInstrs { uint clay_instrs_[]; };

// params and blob concatenated, in that order. Both are float cursors in the
// kernel dialect, and one buffer means one binding and one upload; the host
// passes the base of each in the push constants.
layout(set = 0, binding = 1) readonly buffer ClayFloats { float clay_floats_[]; };

layout(set = 0, binding = 2) readonly buffer ClayIn { float clay_in_[]; };
layout(set = 0, binding = 3) writeonly buffer ClayDist { float clay_dist_[]; };
layout(set = 0, binding = 4) writeonly buffer ClayColor { float clay_color_[]; };

layout(push_constant) uniform ClayPush {
    float origin_x, origin_y, origin_z;
    float spacing;
    uint instr_count;
    uint params_base;
    uint blob_base;
    uint count;
    uint nx, ny, nz;
    uint has_colors;
    // First element this dispatch covers. A batch larger than the device's
    // maxComputeWorkGroupCount is split, and every split writes absolute
    // indices, so a chunked run is indistinguishable from a single one.
    uint base;
} pc;
"""

ENUM_RE = re.compile(r"^enum\s+(\w+)\s*\{")
TYPEDEF_STRUCT_RE = re.compile(r"typedef\s+struct\s+\w+\s*\{(.*?)\}\s*(\w+)\s*;", re.S)
ENTRY_RE = re.compile(r"^\s*(\w+)\s*(?:=\s*([^,]+?))?\s*,?\s*(//.*)?$")


def inline(path: Path, seen: set, out: list) -> None:
    rel = str(path.relative_to(REPO / "include"))
    if rel in seen:
        return
    seen.add(rel)
    out.append(f"// ---- {rel} ----")
    for line in path.read_text().splitlines():
        m = INCLUDE_RE.match(line)
        if m:
            inline(REPO / "include" / m.group(1), seen, out)
            continue
        if line.strip() == "#pragma once":
            continue
        out.append(line)


def rewrite_enums(lines: list) -> list:
    """enum blocks -> const int declarations, keeping every comment."""
    out, i = [], 0
    while i < len(lines):
        m = ENUM_RE.match(lines[i])
        if not m:
            out.append(lines[i])
            i += 1
            continue
        out.append(f"// enum {m.group(1)} (GLSL has no enum; values are unchanged)")
        i += 1
        auto = 0
        while i < len(lines) and not lines[i].strip().startswith("};"):
            body = lines[i]
            stripped = body.strip()
            if not stripped or stripped.startswith("//"):
                out.append(body)
                i += 1
                continue
            em = ENTRY_RE.match(stripped)
            if not em:
                raise SystemExit(f"amalgamate_glsl: cannot parse enumerator {stripped!r}")
            name, value, comment = em.group(1), em.group(2), em.group(3) or ""
            if value is None:
                value = str(auto)
            indent = body[:len(body) - len(body.lstrip())]
            try:
                auto = int(value.strip(), 0) + 1
            except ValueError:
                auto += 1  # an expression: only matters if a later entry omits one
            out.append(f"{indent}const int {name} = {value.strip()};  {comment}".rstrip())
            i += 1
        i += 1  # the closing };
    return out


def rewrite_typedef_structs(text: str) -> str:
    return TYPEDEF_STRUCT_RE.sub(lambda m: f"struct {m.group(2)} {{{m.group(1)}}};", text)


def main() -> int:
    if len(sys.argv) != 4:
        print("usage: amalgamate_glsl.py <entry-header> <output.comp> <entry-points.comp.in>",
              file=sys.stderr)
        return 2
    entry, output, entry_points = sys.argv[1], Path(sys.argv[2]), Path(sys.argv[3])

    lines: list = []
    inline(REPO / "include" / entry, set(), lines)
    lines = rewrite_enums(lines)
    body = rewrite_typedef_structs("\n".join(lines))

    source = PREAMBLE + "\n" + body + "\n// ---- " + entry_points.name + " ----\n" \
        + entry_points.read_text()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(source)
    print(f"amalgamate_glsl: {len(source.encode('utf-8'))} bytes -> {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
